feat: handle hidden plugin
traefik/plugin-service pull request #56
Opened 2024-06-26 13:24 UTC by mmatur

### Description

This PR adds a new property on plugin to allow hidden plugin.

Related to https://github.com/traefik/piceus/pull/65

Co-authored-by: Julien Salleyron <julien.salleyron@gmail.com>

2024-06-26 14:00 UTC, juliens approved these changes
LGTM

2024-07-02 12:57 UTC, kevinpollet requested changes

2024-07-02 12:57 UTC, kevinpollet commented on pkg/db/mongodb/plugindb.go
> +	if !hidden {
I think it would be better to name this parameter `filterHidden` cause when `hidden` is true in my mind I would expect to only have an hidden plugin.

2024-07-02 12:57 UTC, kevinpollet commented on pkg/handlers/handlers.go
> +		hidden = value == "true"
Is it expected here not to use https://pkg.go.dev/strconv#ParseBool?
Maybe the form parameter should also be called `filterHidder`, wdyt?

2024-07-02 13:52 UTC, kevinpollet requested changes

2024-07-02 13:52 UTC, kevinpollet commented on pkg/handlers/dbmock_test.go
> +	return m.getByNameFn(ctx, name, hidden)
```suggestion
func (m mockDB) GetByName(ctx context.Context, name string, _, filterHidden bool) (db.Plugin, error) {
	return m.getByNameFn(ctx, name, filterHidden)
```

2024-07-02 13:52 UTC, kevinpollet commented on pkg/handlers/handlers.go
> +			logger.Error().Err(err).Msg("unable to parse filterHidden field")
```suggestion
			logger.Debug().Err(err).Msg("Unable to parse filterHidden field")
```

2024-07-02 14:03 UTC, kevinpollet approved these changes

2024-07-02 14:04 UTC, merged